def rscript(file)
  sh "cd analysis && Rscript #{file}"
end

namespace :data do
  desc 'Fetch data from the userbase-stats MySQL database'
  task :fetch do
    sh "bin/fetch userbase-stats data"
  end

  desc 'Collect the profile lengths of the processed samples'
  task :length do
    sh "bin/body-length data/processed > data/results/body-length.csv"
  end

  desc 'Segment data into training and testing sets. Define min var beforehand'
  task :segment do
    abort("run as min=XXX rake data:segment") unless ENV['min']
    sh "bin/segment data/processed data/pruned #{ENV['min']} 100"

    %w(training testing).each do |type|
      %w(ham spam).each do |k|
        puts "#{type}: #{k}: " + `ls data/pruned/#{type}/#{k} | wc -l`.strip
      end
    end
  end

  desc 'Marshal data into Ruby objects on the filesystem'
  task :marshal do
    mkdir_p "data/objects"
    sh "bin/marshal data/pruned data/objects"
  end
end

namespace :analyze do
  desc 'Analyze data/results/body-length.csv'
  task :length do
    rscript 'body-length.R'
  end
end

namespace :classifier do
  desc 'Initialize and train a classifier'
  task :train do
    laplace
    sh "bin/train data/objects/training.obj data/objects/classifier.obj"
  end

  desc 'Cross-validate various models'
  task :cross do
    sh "bin/cross-val-models data/objects/training.obj > data/results/models-cv.csv"
  end

  desc 'Test every model'
  task :test do
    sh "bin/test data/objects/training.obj data/objects/testing.obj > data/results/models-test.csv"
  end
end
